# Generated by Django 5.0.2 on 2024-09-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_rename_user_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(unique=True),
        ),
    ]
