# Generated by Django 5.0.2 on 2024-09-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
