# Generated by Django 5.0.2 on 2024-09-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=5)),
            ],
        ),
    ]
